### ISSUE TITLE
Add CI/CD specific email for JSOC

### ISSUE THREAD

**Issue by PaulJWright** [ARCAFF/ARCCnet#65]
CI is failing due to pending export requests on my email. 

I think we can just change it like:

```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use the Environment Variable
        env:
          JSOC_EMAIL: ${{ secrets.<SOME_SECRET_NAME> }}
        run: |
          echo "The value of JSOC_EMAIL is $JSOC_EMAIL"
```

and then our config file can be changed to:

```python
# Check if the environment variable is set
if 'JSOC_EMAIL' in os.environ:
    jsoc_default_email = os.environ['JSOC_EMAIL']
else:
    # If not set, fallback to the value from the configuration file
    jsoc_default_email = dv.JSOC_EMAIL
```
